# Generated by Django 4.0.1 on 2022-01-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='img/')),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
